services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-react
        restart: unless-stopped
        working_dir: /var/www/laravel-react
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - db

    webserver:
        image: nginx:latest
        container_name: laravel-react_webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel-react_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravelReact
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        volumes:
            - laravel-react-db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: lscr.io/linuxserver/phpmyadmin:latest
        container_name: laravel-react_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: laravel
            PMA_PASSWORD: password
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - laravel

    node:
        image: node:18
        container_name: laravel-react_node
        working_dir: /var/www/laravel-react
        volumes:
            - .:/var/www
        networks:
            - laravel
        command: tail -f /dev/null

networks:
    laravel:
        driver: bridge

volumes:
    laravel-react-db-data:
